# Laravel PHP Application Deployment
#
# Custome PHP FMP Docker image, initContainer using same image
# as well as a Busybox image
#
# Inspiration:
# https://itnext.io/scaling-your-symfony-application-and-preparing-it-for-deployment-on-kubernetes-c102bf246a93
# https://www.magalix.com/blog/running-dockerized-laravel-applications-on-top-of-kubernetes
# https://gist.github.com/CodingMonkTech/cafec3a17d2d29f595b01d5b394b0478
# https://lorenzo.aiello.family/running-laravel-on-kubernetes/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: smt-local
  labels:
    tier: backend
spec:
  # Autoscaling
  # autoscale using `kubectl autoscale deployment x --cpu-percent=50 --min=1 --max=10` instead of setting replicas
  # https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
  # replicas: 2 
  selector:
    matchLabels:
      app: web
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: web
        tier: backend
    spec:
      initContainers:
        # args take precedence over commands
      - args:
          - /bin/bash
          - -c
          - (php artisan migrate || true) && (php artisan config:cache || true) && (php
            artisan route:cache || true) && (cp -rp /var/www/. /code)
        envFrom:
          - configMapRef:
              name: laravel-config
        name: install
        image: smart48/smt-laravel:2.1.2
        volumeMounts:
        - name: code-storage
          mountPath: /code
      - name: chown
        image: busybox
        volumeMounts:
        - name: code-storage
          mountPath: /code
        command: ["chown", "-R", "1000:1000", "/code/"]
      containers:
        - name: php
          envFrom:
            - configMapRef:
                name: laravel-config
          image: smart48/smt-laravel:2.1.2
          imagePullPolicy: IfNotPresent
          ports:
            # https://stackoverflow.com/questions/52132193/kubernetes-nginx-php-deployment
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          volumeMounts:
          - name: code-storage
            mountPath: /code
        - name: nginx
          image: nginx:1.19.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: code-storage
            mountPath: /code
          - name: config
            mountPath: /etc/nginx/conf.d
      volumes:
        - name: code-storage
          persistentVolumeClaim:
            claimName: code
        - name: config
          configMap:
            name: nginx-config
            items:
            - key: config
              path: site.conf

